### ISSUE TITLE
Mozilla Firefox, stylesheet didn't work for me. Any ideas?

### ISSUE THREAD

**Issue by Untalia** [Catgrills/Sigma-G#1]
I followed all your steps, (installed the fonts as well).
I am on the latest mozilla browser on Arch Linux.

**Comment by Catgrills** [comment]
Could you take a screenshot of the Stylish page, with the script visible ?

**Comment by Untalia** [comment]
Uh no. Could you tell me how to revert back to the old page?

**Comment by Untalia** [comment]
I reverted back to old youtube. It works now. By the way what's your theme?

**Comment by Catgrills** [comment]
https://github.com/Catgrills/Melbourne-R

**Comment by Untalia** [comment]
Perfect ! It works !
How do you get a new tab? (There is no + sign)(I found a way to bypass this problem with right clicking links)
Should I make a text guide for Linux? (I see you have windows only there)

**Comment by Catgrills** [comment]
i usually used CTRL+T, that's why I hid the new tab button. You could always modify the userChrome.

Sure, I don't mind, it could be useful.
