### ISSUE TITLE
Playlist on the right side of video is fixed and weirdly placed

### ISSUE THREAD

**Issue by LolicoreExpress** [Catgrills/Sigma-G#2]
Hello ! I love your style, but there seems to be a problem with the playlist box on the side of a video.

It is hovering a little bit over the video itself and is also fixed so it stays in place even if I scroll down, so it will also cover the comments :(
Here's a screenshot:  https://i.imgur.com/DNqterq.jpg
Or maybe it's a deliberate design choice ?

PS: I am on Windows 10 using Chrome latest version

**Comment by Catgrills** [comment]
Hey LolicoreExpress,

Thanks for using Sigma-G ! Indeed, it's a deliberate design choice, more or less. If you don't like it, you can modify the style : if you have any difficulties doing it, feel free to ask what's bugging you !

PS : I'm actually redoing a new youtube css (for the new yt layout), here a preview : https://i.4cdn.org/wg/1520292204332.png

**Comment by LolicoreExpress** [comment]
Ah beh c'est parfait x)

Donc c'est fait exprès... Pourquoi pas ! Ahah. 

Mais oui, puisque tu le propose, j'aimerais bien un peu d'aide pour déplacer la boîte playlist, si ça ne te dérange pas. J'ai jeté un coup d'oeil au CSS mais j'ai pas réussi à localiser quoi que ce soit :/ 
Si tu pouvais me dire quoi modifier pour qu'elle soit juste collée à la video [comme ceci](https://i.imgur.com/wyB99Kg.jpg) , ça serait super.

Rapport à ton prochain thème: J'adore le gros relief sur la video, ça la fait vraiment sauter aux yeux, et puis tu garde l'agencement basique intact (video a gauche, colonne de droite...) et je pense que je préfère ça, personnellement ! J'attends avec impatience la release :)

**Comment by Catgrills** [comment]
Pas de soucis ! Cherche simplement "#watch-appbar-playlist" dans le fichier, et modifie la valeur de left : plus la valeur est élevée, plus l'élement ira à droite. 

Merci pour le feedback, le theme est bientôt prêt ! Stay tuned

**Comment by LolicoreExpress** [comment]
C'est bon 👌  
Super, merci beaucoup.

**Comment by Catgrills** [comment]
De rien ! Mais du coup, j'ai publié un nouveau script pour le nouveau Youtube, donc n'hésites pas à l'utiliser !

**Comment by LolicoreExpress** [comment]
Je viens de l'essayer. J'adore ! C'est sobre, smooth. Et j'apprécie particulièrement les textes plus gros. Tout en gardant un peu l'esprit de Youtube Vanilla !
Comme un Youtube 2.0 :D 

Par contre, il fonctionne qu'avec le "nouveau" youtube. Comme ton ancien thème demandait qu'on utilise l'ancienne version de YT je me suis demandé pendant un moment pourquoi ça ne marchait pas 🤔
Peut-être que tu pourrais le préciser dans la description :) 

Beau boulot quoi qu'il en soit ! (au passage tout ce que tu fais est très beau, j'utilise aussi ton thème Google, Soundcloud, 4chan...).

**Comment by Catgrills** [comment]
Content d'entendre tout ça ! Oui, tu as raison, je devrais préciser dans la description que cela ne concerne que le nouveau Youtube.
